server:
  port: 88
spring:
  application:
    name: mall-gateway
  #Nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #网关
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_route
          uri: lb://mall-third
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/api/third/(?<segment>.*),/$\{segment}

        - id: admin_route
          # lb就是负载均衡的意思
          uri: lb://renren-fast
          predicates:
            #只要renren-vue发的请求里面带api，就默认路由到renren-fast
            - Path=/api/**
          filters:
            #路由重写(?<segment>.*)和$\{segment}是正则
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        #nginx路由配置
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com



#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://nz.qq.com/
#          predicates:
#            - Query=url,qq