server:
  port: 88
spring:
  application:
    name: mall-gateway
  #Nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #网关
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://nz.qq.com/
          predicates:
            - Query=url,qq